### ISSUE TITLE
Wont compile on 3.9.1 with dkms on Debian

### ISSUE THREAD

**Issue by psych0d0g** [xapi-project/blktap#36]
blktap does not build with dkms on debian sid with 3.9.1 kernal

   DKMS make.log for blktap-2.0.91 for kernel 3.9-1-amd64 (x86_64)
   Fr 7. Jun 21:08:00 UTC 2013
   make: Entering directory `/usr/src/linux-headers-3.9-1-amd64'
     CC [M]  /var/lib/dkms/blktap/2.0.91/build/control.o
   In file included from /var/lib/dkms/blktap/2.0.91/build/control.c:30:0:
   /var/lib/dkms/blktap/2.0.91/build/blktap.h:75:41: warning: variably modified    'pending' at file scope [enabled by default]
     CC [M]  /var/lib/dkms/blktap/2.0.91/build/ring.o
   In file included from /var/lib/dkms/blktap/2.0.91/build/ring.c:30:0:
   /var/lib/dkms/blktap/2.0.91/build/blktap.h:75:41: warning: variably modified    'pending' at file scope [enabled by default]
   /var/lib/dkms/blktap/2.0.91/build/ring.c: In function 'blktap_ring_map_request':
   /var/lib/dkms/blktap/2.0.91/build/ring.c:206:2: error: too few arguments to    function 'do_mmap_pgoff'
   In file included from /usr/src/linux-headers-3.9-1-   common/include/linux/pagemap.h:7:0,
                    from /usr/src/linux-headers-3.9-1-common/include/linux/blkdev.h:13,
                    from /var/lib/dkms/blktap/2.0.91/build/ring.c:27:
   /usr/src/linux-headers-3.9-1-common/include/linux/mm.h:1454:22: note: declared here
   /var/lib/dkms/blktap/2.0.91/build/ring.c: In function 'blktap_ring_mmap_request':
   /var/lib/dkms/blktap/2.0.91/build/ring.c:438:19: error: 'VM_RESERVED' undeclared (first use in this function)
   /var/lib/dkms/blktap/2.0.91/build/ring.c:438:19: note: each undeclared identifier is reported only once for each function it appears in
   /var/lib/dkms/blktap/2.0.91/build/ring.c: In function 'blktap_ring_mmap_sring':
   /var/lib/dkms/blktap/2.0.91/build/ring.c:474:19: error: 'VM_RESERVED' undeclared (first use in this function)
   make[3]: *** [/var/lib/dkms/blktap/2.0.91/build/ring.o] Error 1
   make[2]: *** [_module_/var/lib/dkms/blktap/2.0.91/build] Error 2
   make[1]: *** [sub-make] Fehler 2
   make: *** [all] Fehler 2
   make: Leaving directory`/usr/src/linux-headers-3.9-1-amd64'
